$(document).ready ->
  $card = undefined
  $cardLike = undefined
  $cardReject = undefined
  animating = undefined
  cardsCounter = undefined
  decisionVal = undefined
  deg = undefined
  numOfCards = undefined
  pullChange = undefined
  pullDeltaX = undefined
  release = undefined
  animating = false
  cardsCounter = 0
  numOfCards = 6
  decisionVal = 80
  pullDeltaX = 0
  deg = 0
  $card = undefined
  $cardReject = undefined
  $cardLike = undefined

  pullChange = ->
    likeOpacity = undefined
    opacity = undefined
    rejectOpacity = undefined
    animating = true
    deg = pullDeltaX / 10
    $card.css 'transform', 'translateX(' + pullDeltaX + 'px) rotate(' + deg + 'deg)'
    opacity = pullDeltaX / 100
    rejectOpacity = if opacity >= 0 then 0 else Math.abs(opacity)
    likeOpacity = if opacity <= 0 then 0 else opacity
    $cardReject.css 'opacity', rejectOpacity
    $cardLike.css 'opacity', likeOpacity
    return

  release = ->
    if pullDeltaX >= decisionVal
      $card.addClass 'to-right'
      registraSwipe()
    else if pullDeltaX <= -decisionVal
      $card.addClass 'to-left'
    if Math.abs(pullDeltaX) >= decisionVal
      $card.addClass 'inactive'
      setTimeout (->
        $card.addClass('below').removeClass 'inactive to-left to-right'
        cardsCounter++
        if cardsCounter == numOfCards
          cardsCounter = 0
          $('.demo__card').removeClass 'below'
        return
      ), 300
    if Math.abs(pullDeltaX) < decisionVal
      $card.addClass 'reset'
    setTimeout (->
      $card.attr('style', '').removeClass('reset').find('.demo__card__choice').attr 'style', ''
      pullDeltaX = 0
      animating = false
      return
    ), 300
    return

  $(document).on 'mousedown touchstart', '.demo__card:not(.inactive)', (e) ->
    startX = undefined
    if animating
      return
    $card = $(this)
    $cardReject = $('.demo__card__choice.m--reject', $card)
    $cardLike = $('.demo__card__choice.m--like', $card)
    startX = e.pageX or e.originalEvent.touches[0].pageX
    $(document).on 'mousemove touchmove', (e) ->
      x = undefined
      x = e.pageX or e.originalEvent.touches[0].pageX
      pullDeltaX = x - startX
      if !pullDeltaX
        return
      pullChange()
      return
    $(document).on 'mouseup touchend', ->
      $(document).off 'mousemove touchmove mouseup touchend'
      if !pullDeltaX
        return
      release()
      return
    return
  return

registraSwipe = ->
  propId = $('#secretito').text()
  arrId = $('#secretito2').text()
  alert propId + ' - ' + arrId
  $.ajax
    type: 'POST'
    url: '/likes'
    data: like:
      propiedad_id: propId
      arrendatario_id: arrId
      fechares: '2017-11-18'
    success: (data) ->
      return
    error: (data) ->
      return
  return

# ---
# generated by coffee-script 1.9.2

# ---
# generated by js2coffee 2.2.0